---
- name: include variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: nginx repository is installed
  yum:
    name: "{{ nginx_repository }}"
    state: present

- name: nginx package is installed
  yum:
    name: nginx
    state: present
    disablerepo: "*"
    enablerepo: nginx

- name: Ensure /etc/pki/nginx
  file:
    path: /etc/pki/nginx
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure /etc/pki/nginx/private
  file:
    path: /etc/pki/nginx/private
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Replace /etc/nginx/nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: /etc/nginx/conf.d/default.conf is removed
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: nginx started
  service:
    name: nginx
    state: started
    enabled: yes
