---
# tasks file for remi
- name: include variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Epel Repository is installed
  yum:
    name: "{{ epel_repository }}"
    state: present
