---
# tasks file for remi
- name: include variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Remi Repository is installed
  yum:
    name: "{{ remi_repository }}"
    state: present
