---
- name: Check if Composer is installed.
  stat:
    path: "{{ composer_path }}"
  register: composer_bin
  become: yes
  become_user: "{{ executor_name }}"

- block:
  - name: Download Composer installer.
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer-installer.php
      mode: 0755
    become: yes
    become_user: "{{ executor_name }}"

  - name: Run Composer installer.
    command: php composer-installer.php
    args:
      chdir: /tmp
      creates: /tmp/composer.phar
    become: yes
    become_user: "{{ executor_name }}"

  - name: Move Composer into globally-accessible location.
    command: mv /tmp/composer.phar "{{ composer_path }}"
    args:
      creates: "{{ composer_path }}"
    become: yes
  when: not composer_bin.stat.exists

- name: Update Composer to latest version (if configured).
  command: php "{{ composer_path }}" self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  become: yes
  become_user: "{{ executor_name }}"
  when: composer_keep_updated | default(False) | bool

- name: Ensure composer directory exists.
  file:
    path: "{{ composer_home_path }}"
    state: directory
  become: yes
  become_user: "{{ executor_name }}"
