---
- name: git dependencies is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ git_dependencies }}"

- name: Regist git_installed_version
  command: git --version
  changed_when: false
  ignore_errors: true
  check_mode: no
  register: git_installed_version

- block:
  - name: Download git
    get_url:
      url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
      dest: "{{ workspace }}/git-{{ git_version }}.tar.gz"

  - name: Expand git archive
    unarchive:
      src: "{{ workspace }}/git-{{ git_version }}.tar.gz"
      dest: "{{ workspace }}"
      creates: "{{ workspace }}/git-{{ git_version }}/README"
      copy: no

  - name: Build git
    command: make prefix={{ git_install_path }} {{ item }}
    args:
      chdir: "{{ workspace }}/git-{{ git_version }}"
    with_items:
      - all
      - install
  when: git_installed_version|failed or git_reinstall
