---
# defaults file for nvm
executor_name: tayutayura
nvm_tmp_dir: /tmp
nvm_script_url: "https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh"
node_version: v9.4.0
node_packages_to_global: []
