---
- name: Regist php_installed_version
  command: php -v
  changed_when: false
  failed_when: false
  check_mode: no
  register: php_installed_version

- name: PHP modules are uninstalled when update php.
  yum:
    name: php*
    state: absent
  when: "php_version|string not in php_installed_version.stdout"

- name: PHP dependencies are installed
  yum:
    name: "{{ php_dependencies }}"
    enablerepo: epel
    state: present

- name: PHP modules are installed
  yum:
    name: "{{ php_modules }}"
    enablerepo: "remi-php{{ php_version|replace('.', '') }}"
    state: present
  notify:
    - restart php-fpm

- name: /etc/php.ini is configured
  lineinfile:
    path: "/etc/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ php_ini_change_lines }}"
  notify:
    - restart php-fpm

- name: /etc/php-fpm.d/www.conf is configured
  lineinfile:
    path: "/etc/php-fpm.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ www_conf_change_lines }}"
  notify:
    - restart php-fpm

- include: phpredis.yml
- include: imagick.yml

- name: php-fpm is started
  service:
    name: php-fpm
    state: started
    enabled: yes
