---
# defaults file for php
executor_name: tayutayura
php_version: 7.2
php_dependencies:
  - re2c
php_modules:
  - php
  - php-devel
  - php-fpm
  - gd-last
  - php-gd
  - php-mbstring
  - php-mysqlnd
  - php-xml
  - php-pear
  - php-pecl-zip
php_imagick_version: 3.4.3
php_ini_change_lines:
  - regexp: '^error_reporting'
    line: 'error_reporting = E_ALL'
  - regexp: '^display_errors'
    line: 'display_errors = On'
  - regexp: '^upload_max_filesize'
    line: 'upload_max_filesize = 8M'
  - regexp: '^;?date.timezone'
    line: 'date.timezone = "Asia/Tokyo"'
  - regexp: '^;?mbstring.language'
    line: 'mbstring.language = Japanese'
  - regexp: '^;?mbstring.internal_encoding'
    line: 'mbstring.internal_encoding = UTF-8'
www_conf_change_lines:
  - regexp: '^user'
    line: "user = {{ executor_name }}"
  - regexp: '^group'
    line: "group = {{ executor_name }}"
  - regexp: '^;?php_admin_value\[memory_limit\]'
    line: 'php_admin_value[memory_limit] = 1024M'
  - regexp: ';?\s?pm\s='
    line: 'pm = static'
  - regexp: ';?\s?pm.max_children\s='
    line: 'pm.max_children = 4'
  - regexp: ';?\s?pm.max_requests\s='
    line: 'pm.max_requests = 500'
